version: '3'
networks:
  todo-stack:
services:
    nuxt:
        build: .
        volumes:
            - ./src:/app/src
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
        networks:
            - todo-stack