version: '3'
volumes:
  php-fpm-socket:
  mongo-db:
  mongo-configdb:
networks:
  todo-stack:
services:
  frontend:
    build:
      context: frontend
      target: production
    restart: always
    ports:
      - 3000:3000
    environment:
      BACKEND_SCHEME: http
      BACKEND_HOST:
  web:
    build:
      context: backend
      dockerfile: docker/web/Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/app
      - ./backend/docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - todo-stack
  app:
    build:
      context: backend
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend/src:/app/src
    networks:
      - todo-stack
    environment:
      TZ: Asia/Tokyo
      LOG_CHANNEL: stderr
      LOG_LEVEL: info
      DB_CONNECTION: mongodb
      APP_DEBUG: 0
      MONGO_DB_HOST:
      MONGO_DB_DATABASE:
      MONGO_DB_USERNAME:
      MONGO_DB_PASSWORD:
  db:
    build:
      context: backend/docker/db
    restart: always
    environment:
      TZ: Asia/Tokyo
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
    ports:
      - 27017:27017
    networks:
      - todo-stack
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb
  db-admin:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - todo-stack
    environment:
      ME_CONFIG_MONGODB_SERVER:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
