version: "3"
volumes:
  php-fpm-socket:
networks:
  todo-stack:
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - todo-stack
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/app
    networks:
      - todo-stack
