name: Build and Push for Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_IMAGE_PREFIX: todo-stack_

jobs:
  push_backend:
    name: Push backend docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [web, app]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate image ID
        run: |
          IMAGE_ID=${{ github.repository }}/${{ env.DOCKER_IMAGE_PREFIX }}${{ matrix.image }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          tags: ${{ env.IMAGE_ID }}
          context: ./backend
          file: ./backend/docker/${{ matrix.image }}/Dockerfile
          push: true

  push_frontend:
    name: Push frontend docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [frontend]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          IMAGE_ID=$DOCKER_REGISTRY/${{ github.repository }}/${{ env.DOCKER_IMAGE_PREFIX }}${{ matrix.image }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag ${{ env.IMAGE_ID}}:latest \
            --target production \
            frontend
          docker push $IMAGE_ID:$IMAGE_VERSION
