name: Build and Push for Server

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_IMAGE_PREFIX: todo-stack_

jobs:
  push_backend:
    # ソースコード一式を Docker コンテナーに封入して GitHub Packages にプッシュする
    name: Push backend docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [web, app]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build image
        working-directory: backend
        
        run: |
          IMAGE_ID=$DOCKER_REGISTRY/${{ github.repository }}/${{ env.DOCKER_IMAGE_PREFIX }}${{ matrix.image }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          IMAGE_VERSION=latest

          docker buildx build \
            --push \
            --platform linux/arm/v7 \
            --file docker/${{ matrix.image }}/Dockerfile --tag $IMAGE_ID:$IMAGE_VERSION . 

  push_frontend:
    # ソースコード一式を Docker コンテナーに封入して GitHub Packages にプッシュする
    name: Push frontend docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [frontend]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build image
        working-directory: frontend
        run: |
          IMAGE_ID=$DOCKER_REGISTRY/${{ github.repository }}/${{ env.DOCKER_IMAGE_PREFIX }}${{ matrix.image }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          IMAGE_VERSION=latest

          docker buildx build \
            --push \
            --platform linux/arm/v7 \
            --target production --tag $IMAGE_ID:$IMAGE_VERSION .
