name: Execute Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

env:
  DOCKER_COMPOSE_FILE: docker-compose.dev.yml

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker-Compose run
        run: |
          sudo chown -R 82:82 ./backend/src
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm -T app composer install
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm -T frontend yarn
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up --build -d

      - name: Wait containers up
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm wait app:8080 -- echo "Backend is up"
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm wait db:27017 -- echo "Database is up"
          docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} run --rm wait frontend:3000 -- echo "Frontend is up"

      - name: Test frontend
        id: frontend
        continue-on-error: true
        run: docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} exec -T frontend yarn test

      - name: Test backend
        id: backend
        continue-on-error: true
        run: docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} exec -T app vendor/bin/phpunit

      - name: Result check of success
        if: steps.frontend.outcome == 'success' && steps.backend.outcome == 'success'
        run: exit 0

      - name: Result check of failure
        if: steps.frontend.outcome != 'success' || steps.backend.outcome != 'success'
        run: exit 1
